'use strict';
const AUTH_STORAGE='rotaryteck-manage-auth-v1';
let authConfig=null,authRefreshPromise=null;
function authRead(){try{return JSON.parse(localStorage.getItem(AUTH_STORAGE)||'null');}catch{return null;}}
function authWrite(value){if(value){localStorage.setItem(AUTH_STORAGE,JSON.stringify(value));document.cookie='rt_access='+encodeURIComponent(value.access_token)+'; Path=/; Max-Age='+Math.max(60,Number(value.expires_in||3600))+'; Secure; SameSite=Strict';}else{localStorage.removeItem(AUTH_STORAGE);document.cookie='rt_access=; Path=/; Max-Age=0; Secure; SameSite=Strict';}}
function authExpired(session){if(!session?.access_token)return true;try{const payload=JSON.parse(atob(session.access_token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return Number(payload.exp||0)*1000<Date.now()+60000;}catch{return true;}}
async function getAuthConfig(){if(authConfig)return authConfig;const r=await fetch('/api/auth/config',{cache:'no-store'}),data=await r.json();if(!r.ok)throw Error(data.error||'登入服務尚未就緒');authConfig=data;return data;}
async function refreshAuth(){if(authRefreshPromise)return authRefreshPromise;authRefreshPromise=(async()=>{const current=authRead();if(!current?.refresh_token)return null;const cfg=await getAuthConfig(),r=await fetch(cfg.url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:current.refresh_token})}),data=await r.json();if(!r.ok){authWrite(null);return null;}authWrite(data);return data;})();try{return await authRefreshPromise;}finally{authRefreshPromise=null;}}
async function authSession(){let session=authRead();if(authExpired(session))session=await refreshAuth();return session;}
async function apiFetch(input,init={}){const session=await authSession();if(!session){showLogin('登入已逾時，請重新登入。');throw Error('請先登入');}const headers=new Headers(init.headers||{});headers.set('Authorization','Bearer '+session.access_token);return fetch(input,{...init,headers});}
function loginField(label,type,name,extra=''){return `<label class="field">${label}<input type="${type}" name="${name}" ${extra}></label>`;}
function showLogin(message=''){$('#cloud-status')?.remove();$('#app').innerHTML=`<main class="login-page"><section class="login-card"><div class="brand"><span class="mark">▤</span><span>Rotaryteck Manage</span></div><h1>登入管理系統</h1><p>使用主管建立的員工帳號登入。</p><form id="login-form">${loginField('登入信箱','email','email','autocomplete="username" required')}${loginField('密碼','password','password','autocomplete="current-password" minlength="8" required')}<button class="primary" type="submit">登入</button><p id="login-error" class="error" role="alert">${message}</p></form></section></main>`;$('#login-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,fd=new FormData(form),button=e.submitter,box=$('#login-error');button.disabled=true;box.textContent='';try{const cfg=await getAuthConfig(),r=await fetch(cfg.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:String(fd.get('email')||'').trim(),password:String(fd.get('password')||'')})}),data=await r.json();if(!r.ok){const reason=data.error_description||data.msg||data.message||data.error||'登入服務沒有提供原因';throw Error(`登入失敗：${reason}`);}authWrite(data);location.reload();}catch(err){box.textContent=err.message||'登入失敗，請稍後重試。';button.disabled=false;}};}
async function ensureAuth(){try{const session=await authSession();if(!session){showLogin();return false;}return true;}catch(e){showLogin(e.message);return false;}}
function logout(){authWrite(null);location.hash='';showLogin('已安全登出。');}
