import fs from 'node:fs';
const workflows=fs.readFileSync('worker/workflows.mjs','utf8').replace(/^export /gm,'');
fs.writeFileSync('dist/workflows.js',workflows);
const codec=fs.readFileSync('worker/state-codec.mjs','utf8').replace(/^export /gm,'');
fs.writeFileSync('dist/state-codec.js',codec);
const names=['manifest.webmanifest','index.html','workflows.js','workflow-ui.js','appearance.js','ui-catalog44.js','release44.css','app.js','style.css','xlsx.full.min.js','favicon.svg','auth.js','cloud.js','admin.js','admin.css','uploads.js','cases.js','audit.js','roles.js','navigation.js','plating.js','state-codec.js','admin-layout.js','plating-ledger.js','wire.js','permissions.js','wire.css','sorting.js','photos.js','controls.css','bulk.js','warehouse-view.js','audit-view.js','warehouse-view.css'];
const types={webmanifest:'application/manifest+json; charset=utf-8',html:'text/html; charset=utf-8',js:'text/javascript; charset=utf-8',css:'text/css; charset=utf-8',svg:'image/svg+xml'};
const assets=Object.fromEntries(names.map(n=>['/'+n,{body:fs.readFileSync('dist/'+n,'utf8'),type:types[n.split('.').pop()]}]));
fs.mkdirSync('dist/server',{recursive:true});
const code=fs.readFileSync('worker/server.mjs','utf8').replace(/^import .*\n/gm,'').replace("return new Response('Not found',{status:404});","const a=assets[path==='/'?'/index.html':path];if(!a)return new Response('Not found',{status:404});return new Response(a.body,{headers:{'Content-Type':a.type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});");
fs.writeFileSync('dist/server/index.js',workflows+'\n'+codec+'\n'+fs.readFileSync('worker/wire-permissions.mjs','utf8').replace(/^import .*\n/gm,'').replace(/^export /gm,'')+'\nconst assets='+JSON.stringify(assets)+';\n'+code);
console.log('Built authenticated warehouse Worker');
