CREATE TABLE IF NOT EXISTS schedule_palette73(id INTEGER PRIMARY KEY CHECK(id=1),colors TEXT NOT NULL,revision INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS schedule_guard73(id TEXT PRIMARY KEY,valid INTEGER NOT NULL CHECK(valid=1));
