import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
function context(){const calls=[],downloads=[],messages=[],ctx=vm.createContext({structuredClone,TextEncoder,TextDecoder,Blob,Uint8Array,Date,console,currentUser:{role:'supervisor'},state:{},renderAdmin(){},canDo:()=>ctx.currentUser.role==='supervisor',authorizeExport:async()=>ctx.currentUser.role==='supervisor',toast:m=>messages.push(m),safeFileName:s=>s,photoStamp:()=> '20261001_2100',receiptTime:v=>v,platingCsv:r=>new TextEncoder().encode(JSON.stringify(r)),makeZip:e=>e,downloadBlob:(e,n)=>downloads.push({entries:e,name:n}),apiFetch:async url=>{calls.push(url);if(url.includes('key='))return new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'image/png'}});if(url.includes('cursor='))return Response.json({items:[{key:'schedule-material/mat/photo',created:'2026-10-01',actor:'倉管',name:'料件.png'},{key:'wire-photos/wire',created:'2026-10-01',actor:'裁線員',name:'wire.png'}],truncated:false});return Response.json({items:[{key:'images/owner/receipts/p/photo',created:'2026-09-30',actor:'甲',name:'收據.png'},{key:'schedule/r/second',created:'2026-10-01',actor:'乙',name:'工作.png'}],truncated:true,cursor:'next'});}});vm.runInContext(fs.readFileSync('dist/admin-layout.js','utf8'),ctx);return{ctx,calls,downloads,messages};}
test('all-photo backup pages through every storage object and includes restorable object manifest',async()=>{const {ctx,downloads,calls}=context();await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);assert.equal(downloads.length,1);const names=downloads[0].entries.map(e=>e.name);assert.equal(names.length,6);assert.equal(new Set(names).size,names.length);assert.ok(names.some(n=>n.startsWith('庫房管理/')));assert.ok(names.some(n=>n.startsWith('工作回報/')));assert.ok(names.some(n=>n.startsWith('每日料件/')));assert.ok(calls.some(n=>n.includes('cursor=next')));const manifest=JSON.parse(new TextDecoder().decode(downloads[0].entries.find(e=>e.name==='物件清單.json').data));assert.equal(manifest.items.length,4);assert.ok(manifest.items.some(m=>m.key==='schedule/r/second'));});
test('failed photo read produces no partial ZIP, and viewer cannot export',async()=>{const {ctx,downloads}=context();const original=ctx.apiFetch;ctx.apiFetch=url=>url.includes('key=')?new Response('{}',{status:500}):original(url);await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);assert.equal(downloads.length,0);ctx.currentUser.role='viewer';ctx.apiFetch=()=>{throw Error('must not call')};await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);assert.equal(downloads.length,0);});
test('saved admin ordering tolerates missing and new sections',()=>{const {ctx}=context();assert.equal(vm.runInContext("orderedAdminKeys(['a','b','c'],['b','b','old','a']).join(',')",ctx),'b,a,c');});
test('wire photo manifest preserves original name, uploader and storage key',async()=>{const {ctx,downloads}=context();await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);const manifest=downloads[0].entries.find(e=>e.name==='照片總表.csv');assert.ok(new TextDecoder().decode(manifest.data).includes('裁線員'));});
