import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
function context(){const calls=[],downloads=[],messages=[],ctx=vm.createContext({structuredClone,TextEncoder,Blob,Uint8Array,Date,console,currentUser:{role:'supervisor'},state:{projects:[{id:'a',name:'同名'}],deletedProjects:[{project:{id:'b',name:'同名'}}],platingProjects:[{id:'p',name:'SJ1',shipments:[{id:'s',number:1}]}]},renderAdmin(){},authorizeExport:async()=>true,toast:m=>messages.push(m),safeFileName:s=>s,photoStamp:()=> '20260923_2100',receiptTime:v=>v,platingPhotoKind:i=>i.kind==='area'?'area':'dispatch',platingPhotoUrl:(p,s)=>'/api/plating-photos?project='+p.id+'&shipment='+s.id,platingCsv:r=>new TextEncoder().encode(JSON.stringify(r)),makeZip:e=>e,downloadBlob:(e,n)=>downloads.push({entries:e,name:n}),apiFetch:async url=>{calls.push(url);if(url==='/api/logo?meta=1')return Response.json({exists:false});if(url.includes('&id='))return new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'image/png'}});if(url.includes('plating-photos'))return Response.json({items:[{id:'d',kind:'dispatch',created:'2026-09-23',actor:'A'},{id:'s',kind:'area',created:'2026-09-23',actor:'B'}]});if(url.includes('cursor='))return Response.json({items:[{id:'two',created:'2026-09-23'}],truncated:false});return Response.json({items:[{id:'one',created:'2026-09-22'}],truncated:true,cursor:'next'});}});vm.runInContext(fs.readFileSync('dist/admin-layout.js','utf8'),ctx);return{ctx,calls,downloads,messages};}
test('all photo export follows pagination and produces unique categorized paths plus manifest',async()=>{const {ctx,downloads,calls}=context();await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);assert.equal(downloads.length,1);const names=downloads[0].entries.map(e=>e.name);assert.equal(names.length,8);assert.equal(new Set(names).size,names.length);assert.ok(names.some(n=>n.startsWith('庫房管理/已刪除案件/')));assert.ok(names.some(n=>n.includes('/第1次送鍍/表面積/')));assert.ok(names.some(n=>n.includes('/第1次送鍍/出貨單/')));assert.ok(calls.some(n=>n.includes('cursor=next')));});
test('failed download produces no partial ZIP; viewer cannot export',async()=>{const {ctx,downloads}=context();ctx.apiFetch=async()=>new Response('{}',{status:500});await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);assert.equal(downloads.length,0);ctx.currentUser.role='viewer';ctx.apiFetch=()=>{throw Error('must not call');};await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);assert.equal(downloads.length,0);});
test('saved admin ordering tolerates missing and new sections',()=>{const {ctx}=context();assert.equal(vm.runInContext("orderedAdminKeys(['a','b','c'],['b','b','old','a']).join(',')",ctx),'b,a,c');});
test('full photo backup includes wire photos with categorized folders and uploader manifest',async()=>{const {ctx,downloads}=context();ctx.state.wireTypes=[{id:'wire',name:'AWG26'}];ctx.state.wireReels=[{id:'r',wireId:'wire',number:'001',color:'紅',photos:[{id:'image',actor:'裁線員',created:'2026-09-24',name:'wire.png'}]}];ctx.wirePhotoUrl=(r,id)=>'/api/wire-photos?reel='+r.id+'&id='+id+'&export=1';await vm.runInContext("exportEveryPhoto({textContent:'匯出',disabled:false})",ctx);assert.equal(downloads.length,1);assert.ok(downloads[0].entries.some(e=>e.name.startsWith('線材管理/001_AWG26/001_001_紅/')));const manifest=downloads[0].entries.find(e=>e.name==='照片總表.csv');assert.ok(new TextDecoder().decode(manifest.data).includes('裁線員'));});
