import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import webpush from 'web-push';
import {database} from './helpers/d1.mjs';
import {migrations85} from './helpers/migrations85.mjs';
import {scheduleApi,scheduleMaterialUpload,schedulePhotoUpload} from '../worker/schedule.mjs';
import {recordsExportApi} from '../worker/records-export.mjs';
import {splitState,joinRecords,diffRecords,stableJSON} from '../worker/state-codec.mjs';
import {notificationPlan85,notificationRulesValid85,notificationClock85} from '../worker/notifications85.mjs';
import {pushSubscriptionApi82,notificationLogApi85,runNotifications85,warehouseChangeAllowed,api,accessApi} from '../worker/server.mjs';
import {builtinProfiles} from '../worker/wire-permissions.mjs';
globalThis.fetch=async(_input,options)=>{const id=new Headers(options.headers).get('authorization')?.slice(7);return Response.json({id,email:id+'@local.test'});};
function fixture(){const {db,DB}=database();migrations85(db);db.exec("INSERT INTO employees(id,account_user_id,email,name,role,status,created_at,updated_at) VALUES(1,'boss','boss@local.test','主管','supervisor','active','now','now'),(2,'staff','staff@local.test','甲','viewer','active','now','now')");db.prepare('INSERT INTO schedule_options(id,items,contents) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET items=excluded.items').run('["FAA","new"]','[]');const files=new Map();const env={DB,SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'test',SUPABASE_SECRET_KEY:'test',UPLOADS:{put:async(k,v)=>files.set(k,v),delete:async k=>files.delete(k),list:async()=>({objects:[],truncated:false})}};const boss={id:1,name:'主管',permissions:builtinProfiles[0].permissions};return{db,DB,env,files,boss};}
const request=(path,body,method='POST',user='boss')=>new Request('https://local.test'+path,{method,headers:{Authorization:'Bearer '+user,origin:'https://local.test','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const work=(id,kind='daily')=>({id,kind,revision:0,day:'2026-10-01',endDay:'2026-10-01',title:'FAA',assignee:'["甲"]',category:'["製作"]',color:'#4e8069',note:''});
test('daily grant cannot rewrite weekly entries through the legacy single endpoint',async()=>{const {env,boss,db}=fixture();assert.equal((await scheduleApi(request('/api/schedule',work('a','weekly')),env,boss)).status,200);const user={id:2,name:'甲',permissions:['schedule.view','schedule.daily.edit']};assert.equal((await scheduleApi(request('/api/schedule',{...work('a'),revision:1}),env,user)).status,400);assert.equal(db.prepare("SELECT kind FROM schedule_entries WHERE id='a'").get().kind,'weekly');});
test('race during batch rejects the entire transaction, including other valid writes',async()=>{const {env,DB,db,boss}=fixture();for(const id of ['a','b'])assert.equal((await scheduleApi(request('/api/schedule',work(id)),env,boss)).status,200);const batch=DB.batch;let injected=false;DB.batch=async statements=>{if(!injected){injected=true;db.exec("UPDATE schedule_entries SET revision=2 WHERE id='a'");}return batch(statements)};const result=await scheduleApi(request('/api/schedule',{kind:'batch',entries:['a','b'].map(id=>({...work(id),revision:1,title:'new'}))}),env,boss);assert.equal(result.status,409);assert.equal(db.prepare("SELECT title FROM schedule_entries WHERE id='b'").get().title,'FAA');assert.equal(db.prepare('SELECT count(*) n FROM schedule_write_guards').get().n,0);});
test('material photo-index failure rolls back the main record and deletes newly uploaded objects',async()=>{const {env,DB,db,boss,files}=fixture();const batch=DB.batch;DB.batch=async()=>{throw Error('index write failed')};const form=new FormData();for(const [k,v]of Object.entries({id:'mat',revision:'0',day:'2026-10-01',title:'螺絲',projectName:'FAA',category:'收料',quantity:'1'}))form.set(k,v);for(let i=0;i<2;i++)form.append('photo',new File(['x'],'p.jpg',{type:'image/jpeg'}));assert.equal((await scheduleMaterialUpload(new Request('https://local.test/api/schedule-material-upload',{method:'POST',headers:{origin:'https://local.test'},body:form}),env,boss)).status,400);assert.equal(db.prepare('SELECT count(*) n FROM schedule_entries').get().n,0);assert.equal(files.size,0);DB.batch=batch;});
test('all ten report photos export and deletion removes every index and object',async()=>{const {env,boss,db,files}=fixture();assert.equal((await scheduleApi(request('/api/schedule',work('a')),env,boss)).status,200);const form=new FormData();for(const [k,v]of Object.entries({id:'r',mode:'create',day:'2026-10-01',entryId:'a',body:'完成'}))form.set(k,v);for(let i=0;i<10;i++)form.append('photo',new File(['x'],'p'+i+'.jpg',{type:'image/jpeg'}));const staff={id:2,name:'甲',permissions:builtinProfiles[2].permissions};assert.equal((await schedulePhotoUpload(new Request('https://local.test/api/schedule-photo-upload',{method:'POST',headers:{origin:'https://local.test'},body:form}),env,staff)).status,200);const exported=await recordsExportApi(request('/api/records-export?from=2026-10-01&to=2026-10-01&types=daily&photos=1',null,'GET'),env,boss,async()=>({}),async()=> 'owner');const result=await exported.json();assert.equal(result.photos.length,10);assert.equal(new Set(result.photos.map(p=>p.url)).size,10);assert.equal((await scheduleApi(request('/api/schedule',{kind:'report',id:'r'},'DELETE'),env,boss)).status,200);assert.equal(db.prepare('SELECT count(*) n FROM schedule_report_photos').get().n,0);assert.equal(files.size,0);});
test('renaming a person preserves the identity of assigned work',async()=>{const {env,boss,db}=fixture();await scheduleApi(request('/api/schedule',work('a')),env,boss);db.exec("UPDATE employees SET name='新名字' WHERE id=2");const response=await scheduleApi(request('/api/schedule?from=2026-10-01&to=2026-10-01',null,'GET'),env,boss);assert.equal(JSON.parse((await response.json()).entries[0].assignee)[0],'新名字');});
test('more than 2000 receipts remain valid and codec changes only the appended receipt and order',()=>{const materialLogs=Array.from({length:2000},(_,i)=>({id:String(i),time:'2026-10-01',actor:'甲',received:[],issued:[]}));const before={projects:[{id:'p',parts:[],inventory:{},materialLogs}],logs:[]},after=structuredClone(before);after.projects[0].materialLogs.unshift({id:'new',time:'2026-10-01',actor:'甲',received:[],issued:[]});assert.equal(warehouseChangeAllowed(before,after),true);assert.equal(stableJSON(joinRecords(splitState(after))),stableJSON(after));assert.equal(diffRecords(before,after).length,2);});
test('production migration preserves old receipt history exactly',async()=>{const {db,env}=fixture();db.exec("INSERT INTO company_state VALUES('warehouse-main','{\"projects\":[],\"logs\":[]}',0,'now')");const legacy={id:'p',parts:[],inventory:{},materialLogs:[{time:'2026-09-30',actor:'甲',received:[],issued:[]}]};db.prepare('INSERT INTO state_records(record_key,body,revision) VALUES(?,?,1)').run('["projects","p"]',JSON.stringify(legacy));db.prepare('INSERT INTO state_records(record_key,body,revision) VALUES(?,?,1)').run('["order","projects"]','["p"]');db.exec(fs.readFileSync('drizzle/0017_material_history85.sql','utf8'));const rows=db.prepare('SELECT record_key,body FROM state_records').all();assert.equal(stableJSON(joinRecords(Object.fromEntries(rows.map(r=>[r.record_key,JSON.parse(r.body)]))).projects[0]),stableJSON(legacy));});
const rule={id:'rule',enabled:true,type:'work',name:'每日提醒',title:'工作',message:'{人員}今天{數量}項工作',time:'08:50',firstDays:0,repeatDays:0,target:'work-record',recipientMode:'auto',recipientIds:[]};
test('notification planner catches up within the day and does not notify people without work',()=>{notificationRulesValid85([rule]);const people=[{id:2,name:'甲',enabled:1},{id:3,name:'乙',enabled:1}],entries=[{...work('a'),assignee_ids:'["2"]'}],clock='2026-10-01T01:00:00Z';assert.deepEqual(notificationClock85(clock),{day:'2026-10-01',time:'09:00'});assert.equal(notificationPlan85([rule],{},entries,[],people,'2026-10-01T00:45:00Z').length,0);const plans=notificationPlan85([rule],{},entries,[],people,clock);assert.equal(plans.length,1);assert.equal(plans[0].employeeId,2);assert.equal(plans[0].message,'甲今天1項工作');assert.equal(notificationPlan85([{...rule,type:'report'}],{},entries,[{entry_id:'a',author_id:'2'}],people,clock).length,0);});
test('person-level pause blocks existing and new devices without losing individual paused state',async()=>{const {env,db}=fixture();const body={endpoint:'https://fcm.googleapis.com/test',p256dh:'x',auth:'x',deviceLabel:'手機'};let r=await pushSubscriptionApi82(request('/api/push-subscription',body,'POST','staff'),env);assert.equal(r.status,200);const id=(await r.json()).id;await pushSubscriptionApi82(request('/api/push-subscription?admin=1',{id,enabled:false},'PATCH'),env);await pushSubscriptionApi82(request('/api/push-subscription?admin=1',{employeeId:2,enabled:false},'PATCH'),env);r=await pushSubscriptionApi82(request('/api/push-subscription',body,'POST','staff'),env);assert.equal((await r.json()).enabled,false);assert.equal(db.prepare('SELECT enabled FROM push_subscriptions WHERE id=?').get(id).enabled,0);r=await pushSubscriptionApi82(request('/api/push-subscription',{...body,endpoint:body.endpoint+'2'},'POST','staff'),env);assert.equal((await r.json()).enabled,false);await pushSubscriptionApi82(request('/api/push-subscription?admin=1',{employeeId:2,enabled:true},'PATCH'),env);assert.equal(db.prepare('SELECT enabled FROM push_subscriptions WHERE id=?').get(id).enabled,0);r=await pushSubscriptionApi82(request('/api/push-subscription?admin=1',null,'GET'),env);const person=(await r.json()).people.find(p=>p.id===2);assert.equal(person.devices.length,2);assert.equal(person.enabled,true);assert.equal(person.devices[0].deviceLabel,'手機');assert.equal((await pushSubscriptionApi82(request('/api/push-subscription?admin=1',null,'GET','staff'),env)).status,403);});
test('subscription cannot silently rebind to another login and missing device changes fail',async()=>{const {env}=fixture();const body={endpoint:'https://fcm.googleapis.com/test',p256dh:'x',auth:'x'};await pushSubscriptionApi82(request('/api/push-subscription',body,'POST','staff'),env);assert.equal((await pushSubscriptionApi82(request('/api/push-subscription',body),env)).status,409);assert.equal((await pushSubscriptionApi82(request('/api/push-subscription?admin=1',{id:'missing',enabled:true},'PATCH'),env)).status,404);});
test('scheduled notifications dedupe across repeated runs and populate admin history',async()=>{const {env,boss,db}=fixture();await scheduleApi(request('/api/schedule',work('a')),env,boss);db.prepare('INSERT INTO company_state VALUES(?,?,0,?)').run('warehouse-main',JSON.stringify({projects:[],logs:[],notificationRules:[rule]}),'now');await pushSubscriptionApi82(request('/api/push-subscription',{endpoint:'https://fcm.googleapis.com/test',p256dh:'x',auth:'x'},'POST','staff'),env);const original=webpush.sendNotification;let count=0;webpush.sendNotification=async()=>{count++};env.VAPID_PUBLIC_KEY=JSON.parse(fs.readFileSync('wrangler.jsonc')).vars.VAPID_PUBLIC_KEY;env.VAPID_PRIVATE_KEY='valid-private-key';env.VAPID_SUBJECT='mailto:test@local.test';try{await runNotifications85(env,'2026-10-01T01:00:00Z');await runNotifications85(env,'2026-10-01T01:05:00Z');assert.equal(count,1);const result=await notificationLogApi85(request('/api/notification-logs',null,'GET'),env);assert.equal((await result.json()).items[0].status,'sent');}finally{webpush.sendNotification=original}});
test('full backup includes schedule, extra photos, permissions and reconstructible history',async()=>{const {env,boss}=fixture();await scheduleApi(request('/api/schedule',work('a')),env,boss);await api(request('/api/state',null,'GET'),env);const response=await accessApi(request('/api/backup-state',null,'GET'),env),backup=await response.json();assert.equal(backup.version,85);assert.equal(backup.tables.schedule_entries.length,1);assert.ok(Array.isArray(backup.tables.schedule_report_photos));assert.ok(Array.isArray(backup.tables.app_employee_settings));});

test('chunked history migration preserves active, deleted and empty project histories',()=>{
 const {db}=fixture();const state={projects:[{id:'large',materialLogs:Array.from({length:3001},(_,i)=>({id:'h'+i,actor:'甲'}))},{id:'empty',materialLogs:[]}],deletedProjects:[{project:{id:'deleted',materialLogs:[{actor:'乙'}]},deletedAt:'now'}],logs:[]};
 for(const [kind,items]of [['projects',state.projects],['deletedProjects',state.deletedProjects]]){for(const item of items)db.prepare('INSERT INTO state_records(record_key,body,revision) VALUES(?,?,1)').run(JSON.stringify([kind,item.id||item.project.id]),JSON.stringify(item));db.prepare('INSERT INTO state_records(record_key,body,revision) VALUES(?,?,1)').run(JSON.stringify(['order',kind]),JSON.stringify(items.map(i=>i.id||i.project.id)));}
 db.exec(fs.readFileSync('drizzle/0017_material_history85.sql','utf8'));const records=Object.fromEntries(db.prepare('SELECT record_key,body FROM state_records').all().map(r=>[r.record_key,JSON.parse(r.body)]));assert.equal(stableJSON(joinRecords(records)),stableJSON(state));
});
test('key rotation retains manager device pause and replaces the same device record',async()=>{
 const {env,db}=fixture();const body={endpoint:'https://fcm.googleapis.com/old',p256dh:'x',auth:'x'};const id=(await(await pushSubscriptionApi82(request('/api/push-subscription',body,'POST','staff'),env)).json()).id;
 await pushSubscriptionApi82(request('/api/push-subscription?admin=1',{id,enabled:false},'PATCH'),env);
 const response=await pushSubscriptionApi82(request('/api/push-subscription',{...body,endpoint:'https://fcm.googleapis.com/new',previousDeviceId:id},'POST','staff'),env);assert.equal(response.status,200);assert.equal((await response.json()).enabled,false);assert.equal(db.prepare('SELECT count(*) n FROM push_subscriptions').get().n,1);assert.equal(db.prepare('SELECT endpoint FROM push_subscriptions').get().endpoint,'https://fcm.googleapis.com/new');
});
test('full backup SQL restores exact tables to a fresh migrated database',async()=>{
 const {restoreSQL85}=await import('../scripts/prepare-restore85.mjs');const {env,boss,db}=fixture();await scheduleApi(request('/api/schedule',work('a')),env,boss);await api(request('/api/state',null,'GET'),env);
 const backup=await(await accessApi(request('/api/backup-state',null,'GET'),env)).json();const target=database().db;migrations85(target);target.exec(restoreSQL85(backup));for(const [table,rows]of Object.entries(backup.tables))assert.equal(stableJSON(target.prepare('SELECT * FROM "'+table+'"').all()),stableJSON(rows),table);
});
