import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {validate,validatePlating,warehouseChangeAllowed} from '../worker/server.mjs';
const shipment=()=>({id:'s1',number:1,vendor:'廠商',sent:'2026-09-23',returned:'',inspection:'pending',note:'',groups:[{sets:2,rings:[{name:'A',qty:10},{name:'B',qty:10},{name:'C',qty:10}]},{sets:3,rings:[{name:'B',qty:15},{name:'C',qty:15}]}]});
const project=()=>({id:'p1',name:'SJ1111',shipments:[shipment()]});
function context(){const ctx={state:{platingProjects:[project()]},currentUser:{role:'supervisor'},render(){},renderAdmin(){},crypto:webcrypto};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../dist/plating.js',import.meta.url),'utf8'),ctx);return ctx;}
test('plating mixed configurations total five fixtures and 150 rings',()=>{const c=context();assert.deepEqual(JSON.parse(JSON.stringify(c.platingTotals(shipment().groups))),{sets:5,pieces:150});validate({projects:[],platingProjects:[project()]});});
test('repeat plating has independent quantities and cleared receipt/QC',()=>{const c=context(),p=project(),source=p.shipments[0];source.returned='2026-09-24';source.inspection='passed';const next=c.platingShipmentDraft(p,source,true);assert.equal(next.number,2);assert.notEqual(next.id,source.id);assert.equal(next.returned,'');assert.equal(next.inspection,'pending');next.groups[0].sets=8;next.groups[0].rings[0].qty=12;assert.equal(source.groups[0].sets,2);assert.equal(source.groups[0].rings[0].qty,10);p.shipments.push(next);validatePlating([p]);});
test('validation rejects duplicate shipment numbers, invalid return dates and unreceived inspection',()=>{for(const mutate of [s=>s.number=0,s=>s.sent='2026-02-30',s=>s.returned='2026-09-22',s=>s.inspection='passed',s=>{s.returned='2026-09-24';s.inspection='abnormal';},s=>s.groups=[],s=>s.groups[0].sets=-1,s=>s.groups[0].rings[0].qty=1.5]){const p=project();mutate(p.shipments[0]);assert.throws(()=>validatePlating([p]));}const p=project();p.shipments.push({...shipment(),id:'s2'});assert.throws(()=>validatePlating([p]));});
test('warehouse can update plating but cannot change settings or other case data',()=>{const before={projects:[],logs:[],cases:[]};const after={...structuredClone(before),platingProjects:[project()]};assert.equal(warehouseChangeAllowed(before,after),true);after.platingText={title:'改名'};assert.equal(warehouseChangeAllowed(before,after),false);delete after.platingText;after.cases.push({name:'unauthorized'});assert.equal(warehouseChangeAllowed(before,after),false);});
test('plating status progresses through receiving and QC; viewer has no edit permission',()=>{const c=context(),s=shipment();assert.equal(c.platingStatus(s),'sending');s.returned='2026-09-24';assert.equal(c.platingStatus(s),'received');s.inspection='abnormal';assert.equal(c.platingStatus(s),'abnormal');s.inspection='passed';assert.equal(c.platingStatus(s),'completed');c.currentUser.role='viewer';assert.equal(c.platingEditAllowed(),false);c.currentUser.role='warehouse';assert.equal(c.platingEditAllowed(),true);});
test('reordering persists the moved project once and ignores busy or viewer requests',async()=>{const c=context();c.state.platingProjects.push({id:'p2',name:'SJ2222',shipments:[]});let saved=0;c.cloudBusy=false;c.failedCandidate=null;c.location={hash:'#plating'};c.addAudit=()=>{};c.saveCloud=async()=>{saved++;};c.render=()=>{};c.toast=()=>{};await c.movePlating('p2','p1');assert.equal(c.state.platingProjects[0].id,'p2');assert.equal(saved,1);c.cloudBusy=true;await c.movePlating('p1','p2');assert.equal(saved,1);c.cloudBusy=false;c.currentUser.role='viewer';await c.movePlating('p1','p2');assert.equal(saved,1);});
test('custom plating text does not alter stored status values',()=>{const c=context();c.state.platingText={title:'表面處理',completed:'驗收完成'};assert.equal(c.pt('title'),'表面處理');const s={...shipment(),returned:'2026-09-24',inspection:'passed'};assert.equal(c.pt(c.platingStatus(s)),'驗收完成');validatePlating([{...project(),shipments:[s]}]);});
