import {test} from 'node:test';
import assert from 'node:assert/strict';
import {database} from './helpers/d1.mjs';
import {api} from '../worker/server.mjs';
import {diffRecords,splitState,joinRecords,normalizeLogIds,stableJSON} from '../worker/state-codec.mjs';
globalThis.fetch=async()=>Response.json({id:'owner',email:'owner@example.com',user_metadata:{name:'主管'}});
const project=id=>({id,name:id,parts:[],inventory:{},archivedParts:[]});
function setup(state={projects:[project('A'),project('B')],logs:[]}){const env={...database(),SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'key',SUPABASE_SECRET_KEY:'secret'};env.db.prepare('INSERT INTO company_state(company_id,body,revision,updated_at) VALUES (?,?,?,?)').run('warehouse-main',JSON.stringify(state),7,new Date().toISOString());return env;}
function request(method='GET',body){return new Request('https://test.local/api/state',{method,headers:{Authorization:'Bearer owner',Origin:'https://test.local','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
const get=async env=>(await api(request(),env)).json();
const payload=(base,next)=>({storageVersion:2,requestId:crypto.randomUUID(),changes:diffRecords(base.state,next,base.versions)});
const put=(env,p)=>api(request('PATCH',p),env);
test('migration preserves original snapshot, custom null, order and missing log IDs',async()=>{const initial={projects:[project('B'),project('A')],custom:null,logs:[{time:'2026-09-23',action:'new'},{time:'2026-09-22',action:'old'}]};const env=setup(initial),a=await get(env),b=await get(env);assert.deepEqual(a,b);assert.deepEqual(a.state.projects,initial.projects);assert.equal(a.state.custom,null);assert.equal(new Set(a.state.logs.map(l=>l.id)).size,2);assert.deepEqual(a.state.logs.map(l=>l.action),['new','old']);assert.deepEqual(JSON.parse(env.db.prepare('SELECT body FROM company_state').get().body),initial);});
test('state larger than 1.5 MB supports a small changed-project request',async()=>{const env=setup({projects:Array.from({length:200},(_,i)=>({...project('P'+i),custom:{note:'x'.repeat(10000)}})),logs:[]});const base=await get(env);assert.ok(JSON.stringify(base.state).length>1500000);const next=structuredClone(base.state);next.projects[0].name='修改';const patch=payload(base,next);assert.equal(patch.changes.length,1);assert.ok(JSON.stringify(patch).length<12000);assert.equal((await put(env,patch)).status,200);assert.equal((await get(env)).state.projects[199].custom.note.length,10000);});
test('concurrent different projects merge; same project conflict is atomic',async()=>{const env=setup(),base=await get(env),a=structuredClone(base.state),b=structuredClone(base.state);a.projects[0].name='甲';b.projects[1].name='乙';a.logs.unshift({id:'l1',detail:'',time:'2026-09-23',action:'甲'});b.logs.unshift({id:'l2',detail:'',time:'2026-09-23',action:'乙'});const responses=await Promise.all([put(env,payload(base,a)),put(env,payload(base,b))]);assert.deepEqual(responses.map(r=>r.status),[200,200]);const result=await get(env);assert.deepEqual(result.state.projects.map(p=>p.name),['甲','乙']);assert.equal(result.state.logs.length,2);a.logs.unshift({id:'l3',detail:'',time:'2026-09-23',action:'不該寫入'});assert.equal((await put(env,payload(base,a))).status,409);assert.deepEqual((await get(env)).state,result.state);});
test('lost-response retry commits once and rejects reused ID with changed content',async()=>{const env=setup(),base=await get(env),next=structuredClone(base.state);next.projects[0].name='改';const p=payload(base,next);const a=await (await put(env,p)).json(),b=await (await put(env,p)).json();assert.deepEqual(a,b);assert.equal((await get(env)).revision,1);p.changes[0].value.name='再改';assert.equal((await put(env,p)).status,409);});
test('SQL failure rolls back all writes and allows retry with same ID',async()=>{const env=setup(),base=await get(env),next=structuredClone(base.state);next.projects[0].name='改';const p=payload(base,next);env.db.exec("CREATE TRIGGER fail_write BEFORE UPDATE ON state_records BEGIN SELECT RAISE(ABORT,'simulated disk failure'); END");assert.equal((await put(env,p)).status,400);assert.deepEqual((await get(env)).state,base.state);assert.equal(env.db.prepare('SELECT count(*) n FROM state_commits').get().n,0);env.db.exec('DROP TRIGGER fail_write');assert.equal((await put(env,p)).status,200);});
test('legacy writes blocked; malformed order rejected; deleted records retain version',async()=>{const env=setup(),base=await get(env);assert.equal((await api(request('PUT',{state:base.state,revision:0}),env)).status,409);const next=structuredClone(base.state);next.projects.shift();const p=payload(base,next);assert.equal((await put(env,{...p,changes:p.changes.filter(c=>!c.deleted)})).status,400);assert.equal((await put(env,p)).status,200);const after=await get(env);assert.equal(after.state.projects.length,1);assert.equal((await put(env,payload(base,{...base.state,projects:[{...project('A'),name:'stale'},project('B')]}))).status,409);});
test('codec preserves null settings and canonical no-op comparisons',()=>{const s=normalizeLogIds({projects:[],logs:[],optional:null});assert.equal(stableJSON(joinRecords(splitState(s))),stableJSON(s));assert.deepEqual(diffRecords(s,structuredClone(s)),[]);const next={projects:[],logs:[]};assert.equal(diffRecords(s,next)[0].deleted,true);});
test('browser retries exact request after timeout and emits only changed records',async()=>{const {default:vm}=await import('node:vm'),{default:fs}=await import('node:fs');const ctx=vm.createContext({crypto,AbortSignal,structuredClone,console});vm.runInContext(fs.readFileSync('worker/state-codec.mjs','utf8').replace(/^export /gm,''),ctx);vm.runInContext(`let state={projects:[{id:'A',name:'A'}],logs:[]},confirmed=structuredClone(state),recordVersions={},pendingSave=null,failedCandidate=null,revision=0,cloudBusy=false,cloudReady=true,queuedToast='';let calls=[],fail=true;const cloudBar=()=>{},render=()=>{},oldToast=()=>{},routeAdmin=()=>{},$=()=>null;async function apiFetch(url,options){calls.push(JSON.parse(options.body));if(fail)throw Error('timeout');return {ok:true,json:async()=>({storageVersion:2,revision:1,versions:Object.fromEntries(calls.at(-1).changes.map(c=>[c.key,c.version+1]))})};}`,ctx);const cloud=fs.readFileSync('dist/cloud.js','utf8');vm.runInContext(cloud.slice(cloud.indexOf('async function sendRecordSave'),cloud.indexOf('persist=function')),ctx);await vm.runInContext('saveCloud(state)',ctx);assert.equal(vm.runInContext('calls.length',ctx),0);await vm.runInContext("state.projects[0].name='changed';saveCloud(state)",ctx);assert.equal(vm.runInContext('state.projects[0].name',ctx),'A');await vm.runInContext('fail=false;retryRecordSave()',ctx);assert.equal(vm.runInContext('JSON.stringify(calls[0])===JSON.stringify(calls[1])',ctx),true);assert.equal(vm.runInContext('state.projects[0].name',ctx),'changed');assert.equal(vm.runInContext('calls[0].changes.length',ctx),1);});
