import {test} from 'node:test';import assert from 'node:assert/strict';
import {database} from './helpers/d1.mjs';
import {api,permissionsApi,wireImages,accessApi,employeesApi,validate} from '../worker/server.mjs';
import {diffRecords,normalizeLogIds} from '../worker/state-codec.mjs';
import {wireChangeAllowed} from '../worker/wire-permissions.mjs';
globalThis.fetch=async(input,init)=>{const id=new Headers(init.headers).get('authorization')?.slice(7);return Response.json({id,email:id+'@example.com'});};
function setup(){const {db,DB}=database(),files=new Map();for(const role of ['supervisor','warehouse','viewer','other'])db.prepare('INSERT INTO employees(account_user_id,email,name,role,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(role,role+'@example.com',role,role==='other'?'viewer':role,'active','now','now');return {db,DB,SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'key',SUPABASE_SECRET_KEY:'secret',files,UPLOADS:{async head(k){return files.get(k)},async put(k,body,options){files.set(k,{...options,body});},async get(k){return files.get(k)}}};}
function req(path,user='supervisor',method='GET',body){return new Request('https://test.local'+path,{method,headers:{Authorization:'Bearer '+user,Origin:'https://test.local','Content-Type':'application/json','X-File-Name':'test.png'},...(body!==undefined?{body:body instanceof Uint8Array?body:JSON.stringify(body)}:{})});}
const read=async(env,user='supervisor')=>await(await api(req('/api/state',user),env)).json();
async function save(env,before,next,user='supervisor'){normalizeLogIds(next);return api(req('/api/state',user,'PATCH',{storageVersion:2,requestId:crypto.randomUUID(),changes:diffRecords(before.state,next,before.versions)}),env);}
async function initialize(env){const first=await read(env);const next={...first.state,cases:[],platingProjects:[],wireTypes:[{id:'type',name:'AWG26'}],wireReels:[{id:'reel',wireId:'type',number:'001',color:'紅',status:'enough',photos:[]}],wireCuts:[]};assert.equal((await save(env,first,next)).status,200);}
async function photo(env,user='viewer'){const res=await wireImages(req('/api/wire-photos?reel=reel',user,'POST',new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0])),env);assert.equal(res.status,201);return res.json();}
function addCut(data,p,user){const next=structuredClone(data.state);next.wireReels[0].photos.push(p);next.wireCuts.unshift({id:crypto.randomUUID(),reelId:'reel',actor:user,actorId:p.actorId,time:p.created,length:50,quantity:10,photoId:p.id});next.logs.unshift({id:crypto.randomUUID(),time:p.created,actor:user,action:'新增裁線紀錄',detail:'50 cm × 10',project:'wire:type',location:'線材管理'});return next;}
test('cut requires a real uploaded photo; saving record+photo is atomic and actor is enforced',async()=>{const env=setup();await initialize(env);const first=await read(env,'viewer'),p=await photo(env),next=addCut(first,p,'viewer');let invalid=structuredClone(next);invalid.wireCuts[0].photoId=crypto.randomUUID();assert.equal((await save(env,first,invalid,'viewer')).status,400);assert.equal((await read(env)).state.wireCuts.length,0);invalid=structuredClone(next);invalid.wireCuts[0].actor='supervisor';assert.equal((await save(env,first,invalid,'viewer')).status,403);assert.equal((await save(env,first,next,'viewer')).status,200);const stored=await read(env);assert.equal(stored.state.wireCuts.length,1);assert.equal(stored.state.wireReels[0].photos.length,1);assert.equal((await wireImages(req('/api/wire-photos?reel=reel&id='+p.id,'viewer'),env)).status,200);assert.equal((await wireImages(req('/api/wire-photos?reel=reel&id='+p.id+'&export=1','viewer'),env)).status,403);});
test('staff flags low; warehouse and supervisor restore enough; staff edits only own cuts and cannot mutate old photos',async()=>{const env=setup();await initialize(env);let before=await read(env,'viewer'),p=await photo(env);assert.equal((await save(env,before,addCut(before,p,'viewer'),'viewer')).status,200);before=await read(env);let next=structuredClone(before.state);next.wireReels[0].status='low';assert.equal((await save(env,before,next,'viewer')).status,200);before=await read(env);next=structuredClone(before.state);next.wireReels[0].status='enough';assert.equal((await save(env,before,next,'viewer')).status,403);assert.equal((await save(env,before,next,'warehouse')).status,200);before=await read(env);next=structuredClone(before.state);next.wireCuts[0].quantity=20;next.wireCuts[0].updatedBy='other';next.wireCuts[0].updatedAt=new Date().toISOString();assert.equal((await save(env,before,next,'other')).status,403);next.wireCuts[0].updatedBy='viewer';assert.equal((await save(env,before,next,'viewer')).status,200);before=await read(env);next=structuredClone(before.state);next.wireReels[0].photos[0].actor='other';assert.equal((await save(env,before,next,'viewer')).status,403);next=structuredClone(before.state);next.wireReels[0].photos=[];assert.equal((await save(env,before,next,'supervisor')).status,400);});
test('custom profiles enforce views, writes, no export, protected status, and directory ordering',async()=>{const env=setup();await initialize(env);const p=await permissionsApi(req('/api/permissions','supervisor','POST',{name:'線材登記員',permissions:['wire.view','wire.cut','wire.photos','wire.editOwn']}),env);assert.equal(p.status,200);const {id}=await p.json();const viewer=env.db.prepare("SELECT id FROM employees WHERE account_user_id='viewer'").get();env.db.prepare('INSERT INTO app_employee_settings(employee_id,profile_id,position) VALUES(?,?,?)').run(viewer.id,id,0);let data=await read(env,'viewer');assert.equal(data.currentUser.roleLabel,'線材登記員');assert.deepEqual(data.state.platingProjects,[]);let next=structuredClone(data.state);next.wireReels[0].status='low';assert.equal((await save(env,data,next,'viewer')).status,200);data=await read(env,'viewer');const img=await photo(env);assert.equal((await save(env,data,addCut(data,img,'viewer'),'viewer')).status,200);assert.equal((await accessApi(req('/api/export-access','viewer'),env)).status,403);assert.equal((await permissionsApi(req('/api/permissions','viewer','POST',{name:'升級',permissions:[]}),env)).status,403);assert.equal((await permissionsApi(req('/api/permissions','supervisor','DELETE',{id}),env)).status,400);const ids=env.db.prepare('SELECT id FROM employees ORDER BY id DESC').all().map(e=>e.id);assert.equal((await permissionsApi(req('/api/permissions','supervisor','POST',{order:ids}),env)).status,200);const directory=await(await accessApi(req('/api/employee-options','viewer'),env)).json();assert.deepEqual(directory.items.map(e=>e.id),ids);assert.equal((await permissionsApi(req('/api/permissions','supervisor','POST',{name:'僅裁線登記',permissions:['wire.view','wire.cut']}),env)).status,200);});
test('photo read/upload denied without wire view, no forged or cross-reel photo can be saved',async()=>{const env=setup();await initialize(env);let before=await read(env),p=await photo(env),next=addCut(before,p,'viewer');next.wireReels[0].photos[0].name='forged.png';assert.equal((await save(env,before,next,'viewer')).status,400);const id=crypto.randomUUID();env.db.prepare('INSERT INTO app_permission_profiles VALUES(?,?,?)').run(id,'無線材','[]');env.db.prepare('INSERT INTO app_employee_settings VALUES(?,?,?)').run(3,id,0);assert.equal((await wireImages(req('/api/wire-photos?reel=reel','viewer'),env)).status,403);});
test('quantity validation and independent record storage preserve photos and prevent empty-spool deletion loss',()=>{const state={projects:[],wireTypes:[{id:'t',name:'AWG26'}],wireReels:[{id:'r',wireId:'t',number:'1',color:'red',status:'enough',photos:[]}],wireCuts:[]};validate(state);const after=structuredClone(state);after.wireReels[0].status='low';assert.equal(wireChangeAllowed(state,after,{id:1,role:'viewer',permissions:['wire.edit']}),false);assert.equal(wireChangeAllowed(state,after,{id:1,role:'warehouse',permissions:[]}),true);const next=structuredClone(state);next.wireTypes[0].name='AWG28';assert.deepEqual(diffRecords(state,next,{}).map(c=>JSON.parse(c.key)[0]),['wireTypes']);});
test('committed photos leave staging queue atomically; abandoned uploads expire without deleting saved photos',async()=>{const env=setup();env.UPLOADS.delete=async k=>env.files.delete(k);await initialize(env);const before=await read(env,'viewer'),p=await photo(env);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM wire_pending_uploads').get().n,1);assert.equal((await save(env,before,addCut(before,p,'viewer'),'viewer')).status,200);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM wire_pending_uploads').get().n,0);const abandoned=await photo(env);env.db.prepare('UPDATE wire_pending_uploads SET created_at=? WHERE id=?').run('2020-01-01T00:00:00.000Z',abandoned.id);await photo(env);assert.equal(env.files.has('wire-photos/'+abandoned.id),false);assert.equal(env.files.has('wire-photos/'+p.id),true);});
test('simultaneous cuts on different spools do not conflict on a shared newest-first order',async()=>{const env=setup();await initialize(env);let before=await read(env),next=structuredClone(before.state);next.wireReels.push({id:'reel2',wireId:'type',number:'002',color:'黑',status:'enough',photos:[]});assert.equal((await save(env,before,next)).status,200);const a=await read(env,'viewer'),b=await read(env,'other'),pa=await photo(env),res=await wireImages(req('/api/wire-photos?reel=reel2','other','POST',new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,0])),env),pb=await res.json();const na=addCut(a,pa,'viewer'),nb=addCut(b,pb,'other');nb.wireReels[0].photos=[];nb.wireReels[1].photos.push(pb);nb.wireCuts[0].reelId='reel2';assert.equal((await save(env,a,na,'viewer')).status,200);assert.equal((await save(env,b,nb,'other')).status,200);assert.equal((await read(env)).state.wireCuts.length,2);});
test('built-in permission buttons are configurable, persist order, and never grant supervisor export to other roles',async()=>{const env=setup();await initialize(env);let list=await(await permissionsApi(req('/api/permissions'),env)).json();assert.deepEqual(list.items.map(p=>p.id),['supervisor','warehouse','viewer']);assert(list.items.every(p=>p.builtin));let r=await permissionsApi(req('/api/permissions','supervisor','POST',{id:'warehouse',name:'倉管',permissions:['wire.view']}),env);assert.equal(r.status,200);let before=await read(env,'warehouse');assert.deepEqual(before.currentUser.permissions,['wire.view']);assert.equal((await photoDenied()).status,403);async function photoDenied(){return wireImages(req('/api/wire-photos?reel=reel','warehouse','POST',new Uint8Array([137,80,78,71,13,10,26,10])),env);}assert.equal((await accessApi(req('/api/export-access','warehouse'),env)).status,403);assert.equal((await permissionsApi(req('/api/permissions','supervisor','DELETE',{id:'warehouse'}),env)).status,400);const order=['viewer','supervisor','warehouse'];assert.equal((await permissionsApi(req('/api/permissions','supervisor','POST',{profileOrder:order}),env)).status,200);list=await(await permissionsApi(req('/api/permissions'),env)).json();assert.deepEqual(list.items.map(p=>p.id),order);
 assert.equal((await permissionsApi(req('/api/permissions','supervisor','POST',{id:'supervisor',name:'主管',permissions:['wire.view']}),env)).status,200);before=await read(env);const next=structuredClone(before.state);next.wireTypes[0].name='無權修改';assert.equal((await save(env,before,next)).status,403);assert.equal((await accessApi(req('/api/export-access'),env)).status,200);assert.equal((await permissionsApi(req('/api/permissions'),env)).status,200);assert.equal((await accessApi(req('/api/backup-state'),env)).status,200);
});

test('multiple photo-free cuts save atomically; invalid batch rejected and photo can be attached later',async()=>{
 const env=setup();await initialize(env);let first=await read(env,'viewer'),next=structuredClone(first.state);
 const base={reelId:'reel',actor:'viewer',actorId:String(first.currentUser.id),time:new Date().toISOString(),photoId:''};
 next.wireCuts=[{...base,id:'no-photo-a',length:25,quantity:10},{...base,id:'no-photo-b',length:60,quantity:4}];
 const invalid=structuredClone(next);invalid.wireCuts[1].quantity=1.5;assert.equal((await save(env,first,invalid,'viewer')).status,400);assert.equal((await read(env)).state.wireCuts.length,0);
 assert.equal((await save(env,first,next,'viewer')).status,200);assert.equal((await read(env)).state.wireCuts.length,2);
 const uploaded=await photo(env);first=await read(env,'viewer');next=structuredClone(first.state);next.wireReels[0].photos.push(uploaded);const c=next.wireCuts.find(x=>x.id==='no-photo-a');Object.assign(c,{photoId:uploaded.id,updatedAt:new Date().toISOString(),updatedBy:'viewer'});assert.equal((await save(env,first,next,'viewer')).status,200);const saved=await read(env);assert.equal(saved.state.wireCuts.find(x=>x.id==='no-photo-a').photoId,uploaded.id);assert.equal(saved.state.wireCuts.find(x=>x.id==='no-photo-b').photoId,'');
});
test('cut permission works without photo permission; can flag low but cannot clear it or export',async()=>{
 const env=setup();await initialize(env);assert.equal((await permissionsApi(req('/api/permissions','supervisor','POST',{id:'viewer',name:'一般員工',permissions:['wire.view','wire.cut','wire.editOwn']}),env)).status,200);
 const first=await read(env,'viewer'),next=structuredClone(first.state);next.wireCuts=[{id:'cut-only',reelId:'reel',actor:'viewer',actorId:String(first.currentUser.id),time:new Date().toISOString(),photoId:'',length:20,quantity:2}];assert.equal((await save(env,first,next,'viewer')).status,200);
 const current=await read(env,'viewer'),changed=structuredClone(current.state);changed.wireReels[0].status='low';assert.equal((await save(env,current,changed,'viewer')).status,200);const low=await read(env,'viewer'),enough=structuredClone(low.state);enough.wireReels[0].status='enough';assert.equal((await save(env,low,enough,'viewer')).status,403);assert.equal((await accessApi(req('/api/export-access','viewer'),env)).status,403);
});
