import {test} from 'node:test';import assert from 'node:assert/strict';
import {database} from './helpers/d1.mjs';import {api} from '../worker/server.mjs';import {restockTransition} from '../worker/workflows.mjs';import {diffRecords} from '../worker/state-codec.mjs';
globalThis.fetch=async(input,init)=>{const id=new Headers(init.headers).get('authorization')?.slice(7);return Response.json({id,email:id+'@example.com'});};
function setup(){const {db,DB}=database();for(const role of ['supervisor','warehouse','viewer'])db.prepare('INSERT INTO employees(account_user_id,email,name,role,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(role,role+'@example.com',role,role,'active','now','now');return {db,DB,SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'key',SUPABASE_SECRET_KEY:'secret'};}
const req=(role,method='GET',body)=>new Request('https://test.local/api/state',{method,headers:{Authorization:'Bearer '+role,Origin:'https://test.local','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const read=async(env,role='supervisor')=>(await api(req(role),env)).json();
const save=(env,base,state,role='supervisor')=>api(req(role,'PATCH',{storageVersion:2,requestId:crypto.randomUUID(),changes:diffRecords(base.state,state,base.versions)}),env);
async function init(env){const b=await read(env),s={...b.state,wireTypes:[{id:'t',name:'AWG26'}],wireReels:[{id:'r',wireId:'t',number:'1',color:'黑',status:'enough',photos:[]}],wireCuts:[]};assert.equal((await save(env,b,s)).status,200);}
test('API persists complete restock round, enforces actor/role and rejects competing same-reel update',async()=>{const env=setup();await init(env);let b=await read(env,'viewer'),n=structuredClone(b.state);assert(Number.isFinite(Date.parse(b.serverTime)));n.wireReels[0]=restockTransition(n.wireReels[0],'low',b.currentUser,new Date().toISOString(),'round');assert.equal((await save(env,b,n,'viewer')).status,200);
 b=await read(env,'warehouse');n=structuredClone(b.state);n.wireReels[0]=restockTransition(n.wireReels[0],'order',b.currentUser,new Date().toISOString());assert.equal((await save(env,b,n,'warehouse')).status,200);const competing=structuredClone(b.state);competing.wireReels[0]=restockTransition(competing.wireReels[0],'receive',b.currentUser,new Date().toISOString());assert.equal((await save(env,b,competing,'warehouse')).status,409);
 b=await read(env,'viewer');n=structuredClone(b.state);n.wireReels[0]=restockTransition(n.wireReels[0],'receive',{...b.currentUser,role:'warehouse'},new Date().toISOString());assert.equal((await save(env,b,n,'viewer')).status,403);
 b=await read(env,'warehouse');n=structuredClone(b.state);n.wireReels[0]=restockTransition(n.wireReels[0],'receive',b.currentUser,new Date().toISOString());assert.equal((await save(env,b,n,'warehouse')).status,200);const result=await read(env);assert.equal(result.state.wireReels[0].restock.events.length,3);assert.equal(result.state.wireReels[0].status,'enough');});
test('API blocks new shipment without welder and permits valid shipment',async()=>{const env=setup();let b=await read(env),n=structuredClone(b.state);n.platingProjects=[{id:'p',name:'SJ1',shipments:[{id:'s',vendor:'廠商',number:1,sent:'2026-09-25',returned:'',inspection:'pending',note:'',groups:[{sets:1,rings:[{name:'R',qty:1}]}]}]}];assert.equal((await save(env,b,n)).status,403);Object.assign(n.platingProjects[0].shipments[0],{welderId:'2',welderName:'warehouse'});assert.equal((await save(env,b,n)).status,200);});
test('API stock correction preserves production baseline and cannot alter manufacturing settings',async()=>{const env=setup();let b=await read(env),n=structuredClone(b.state);n.projects=[{id:'p',name:'P',parts:[{id:'i',name:'零件',spec:'',need:2,sets:3,received:10}],inventory:{i:6},archivedParts:[],production:{id:'round',start:'2026-09-25',sets:3,baseline:{i:{stock:4,received:8}}}}];assert.equal((await save(env,b,n)).status,200);b=await read(env,'warehouse');n=structuredClone(b.state);n.projects[0].parts[0].received-=2;n.projects[0].inventory.i-=2;n.projects[0].materialLogs=[{id:'fix',time:new Date().toISOString(),actor:'warehouse',received:[],issued:[],correction:{partId:'i',delta:-2,reason:'誤填'}}];assert.equal((await save(env,b,n,'warehouse')).status,200);b=await read(env,'warehouse');n=structuredClone(b.state);n.projects[0].production.baseline.i.stock=100;assert.equal((await save(env,b,n,'warehouse')).status,403);});
